### ISSUE TITLE
 is there any file size limit?

### ISSUE THREAD

**Issue by alex2wong** [jankais3r/RDPcopy#1]
Hi, it is really nice to find such a good :+1:  repo. I was doing some research on filetransfer on html5 RDP (based on websocket). 

I found if transfering big file (over 10kb), the socket frame would fail in **frame constructing** process.  btw, what RDP tools did you use ? ? thx :smile:

**Comment by jankais3r** [comment]
Hi Alex,

these scripts were designed to be used with Microsoft's RDP client (mstsc.exe) or any other client that can access clipboard on both the local and remote systems.

Good luck!

**Comment by alex2wong** [comment]
thx, got it : )
